## NumPy Recap

In [3]:
import numpy as np

# create a random numpy array with 1000 numbers between 0 and 100 (inclusive)
array = np.random.randint(0, 101, 1000)

# print the array
print(array)

[ 44  57  84  67  84  12  78  24  14  31  25  67  50  51  94  85  73  14
   2  13  43  39  29   9  85  36  11  62  20   2  38  37  31  51  24   0
  80   5  99  20  79   5  49  15  26  67  94 100  15  84  40  12  43  48
  38  19  82  35  81   2  62  67  81  64  33  49  10  42  88  33  36  93
  13  66  87  96  30  84  16  22  34  98  98  25  71  70  89  61  32  36
  39  24  25  29  36  63  57  58  48  95  76  70  66  95  40  48  95  41
  54  11  18  72  81  98  69  24  84  20   8  26  13  59  70  24  17   3
   4  84  99  52  49   8  82  63  37  98  79  81  74  75  24  33  97  72
  25  97  83  83  27  82  27   4  83  69   5  24  37  16  72  42  61  70
  10 100  60  34  55  79  25  95  63  56  64  48  27  18  80  17  46  69
  27  93  90  71  53  73  69  96  36  42  54  61   3  71  32  81   0   6
  93  90   5  83  88  83  97  10  92  78  23  22   2  26  76  98  51  70
  88  18  11  31   4  28  98   1   2  38  74  89  36  95  12  58   7  56
  25   3  41  79  22   6  32  79  63  75  94   8  6

In [2]:
# mandatory imports
import numpy as np

### Erstellung N-dimensional NumPy Arrays

1) Gesucht ist folgendes Ergebnis:

```
array([1, 2, 3, 4], dtype=int32)
```

In [3]:
#1) a vector: the argument to the array function is a Python list
lst = [1,2,3,4.0]
lst = np.array(lst, 'int32')
print(lst)

[1 2 3 4]


Geben Sie den Datentyp des Arrays aus:

```
dtype('int32')
```

In [4]:
# get its datatype
lst.dtype

dtype('int32')

2) Gesucht ist folgendes Ergebnis:

```
array([[1, 2],
       [3, 4]])
```

In [5]:
#2) a matrix: the argument to the array function is a nested Python list (can also be a tuple of tuples)
np.arange(1, 5).reshape(2, 2)

array([[1, 2],
       [3, 4]])

3) Gesucht ist folgendes Ergebnis:
```
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])
```

In [6]:
#3) an array full of zero values
np.zeros([3, 4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

#### A note on datatypes
If no datatype is specified during array construction using `np.array()`, NumPy assigns a default dtype. This is dependent on the OS (32 or 64 bit) and the elements of the array.

In [7]:
# get the list of all supported data types
np.sctypes

{'int': [numpy.int8, numpy.int16, numpy.int32, numpy.int64],
 'uint': [numpy.uint8, numpy.uint16, numpy.uint32, numpy.uint64],
 'float': [numpy.float16, numpy.float32, numpy.float64],
 'complex': [numpy.complex64, numpy.complex128],
 'others': [bool, object, bytes, str, numpy.void]}

### Array slicing

4) Gesucht ist folgendes Ergebnis:

```
array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45]])
```

Verwenden Sie hierzu `arange` in Kombination mit `reshape`. 

In [8]:
#4)
array = np.arange(1, 46).reshape(3, 15)
array

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45]])

5) Selektieren Sie! By the way: Die Indizierung eines 2-D benötigt 2 Indizes.

In [9]:
# value at last row and last column
array[-1, -1]

45

In [10]:
# get all elments in the last row
array[-1,]

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45])

In [11]:
# get the value 23 
array[array == 23][0]

23

In [12]:
# get the first two rows and 3 columns
array[:2,:3]

array([[ 1,  2,  3],
       [16, 17, 18]])

In [13]:
# get following matrix
# array([[ 7,  8,  9],
#       [22, 23, 24],
#       [37, 38, 39]])
array[:3,6:9]

array([[ 7,  8,  9],
       [22, 23, 24],
       [37, 38, 39]])

### Computing statistics

6) Erstellen Sie folgende Matrix:

```
array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])
```


In [14]:
#6)
array = np.arange(0, 30).reshape(5,6)
array

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

Berechnen Sie den Mittelwert für die Achse 0, also spaltenweise. Gesuchtes Ergebnis:
``` array([[12., 13., 14., 15., 16., 17.]]) ```

Verwenden Sie hierzu https://numpy.org/doc/stable/reference/generated/numpy.mean.html

In [15]:
array.mean(axis=0)

array([12., 13., 14., 15., 16., 17.])

### Just for fun

Erstellen Sie ein 3x3 Pixel großes SW-Bild; wobei ausschließlich mittlere Pixel weiß ist (siehe unten). Es gilt:
- 0 = sw
- 1 = weiß

In [ ]:
# Hint: Matrix is not just a movie!
img = np.zeros([3,3])
middle = (int(img.shape[0] / 2), int(img.shape[1] / 2))
img[middle[0], middle[1]] = 1


import matplotlib.pyplot as plt
plt.imshow(img,cmap="gray")